name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.pair.os }}
    strategy:
      fail-fast: false
      matrix:
        pair:
          - erlang: master
            rebar3: 3.25.0
            os: ubuntu-24.04

          - erlang: 28
            rebar3: 3.25.0
            os: ubuntu-24.04
            lint: true

          - erlang: 27
            rebar3: 3.23.0
            os: ubuntu-22.04

          - erlang: 26
            rebar3: 3.21.0
            os: ubuntu-22.04

          - erlang: 25
            rebar3: 3.21.0
            os: ubuntu-22.04

          - erlang: 24
            rebar3: 3.21.0
            os: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@ee09b1e59bb240681c382eb1f0abc6a04af72764 # v1.23.0
        with:
          otp-version: ${{ matrix.pair.erlang }}
          rebar3-version: ${{ matrix.pair.rebar3 }}

      - run: rebar3 ct
      - run: rebar3 as test proper
      - run: rebar3 fmt --check
        if: ${{ matrix.pair.lint }}
